# Appearance
set -g status-position top
set -g status-style "bg=brightblack,fg=white"

set -g status-left " "

set -g renumber-windows on
set -g window-status-separator " | "
set -g window-status-format "#{b:pane_current_path}#F"
set -g window-status-current-style "bg=gray,fg=black"
set -g window-status-current-format "#{pane_current_path}#F"
set -g display-panes-time 5000
set -g display-time 5000

set -g pane-border-style "fg=brightblack"

# Navigation
set -g mode-keys vi
set -g mouse on

bind s split-window
bind v split-window -h

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r Up resize-pane -U 3
bind -r Down resize-pane -D 3
bind -r Left resize-pane -L 3
bind -r Right resize-pane -R 3

bind S choose-session
